# Use postgres/example user/password credentials
version: '3.1'

services:

  auth:
    image: postgres
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
